export const initialCategories = [
  { id: 'cat-1', name: 'Pain Relief', description: 'Analgesics and pain relievers for headache, muscle ache, joint pain.' },
  { id: 'cat-2', name: 'Fever & Antipyretics', description: 'Medicines to reduce fever and body temperature.' },
  { id: 'cat-3', name: 'Cold & Cough', description: 'Antihistamines, decongestants, and cough syrups.' },
  { id: 'cat-4', name: 'Allergy & Asthma', description: 'Anti-allergy medication, nasal sprays, and inhalers.' },
  { id: 'cat-5', name: 'Gastric & Acidity', description: 'Antacids, proton pump inhibitors, and anti-reflux meds.' },
  { id: 'cat-6', name: 'Vitamins & Supplements', description: 'Essential daily vitamins, minerals, and dietary supplements.' },
  { id: 'cat-7', name: 'Diabetes Care', description: 'Insulin, oral hypoglycemics, and blood sugar testing supplies.' },
  { id: 'cat-8', name: 'Blood Pressure & Heart', description: 'Antihypertensives, cardio-protective medications.' },
  { id: 'cat-9', name: 'Skin Care & Ointments', description: 'Topical creams, ointments, antifungal gels, and antiseptics.' },
  { id: 'cat-10', name: 'Eye & Ear Care', description: 'Sterile drops and ointments for ophthalmic and otic use.' },
  { id: 'cat-11', name: 'Digestive Health', description: 'Laxatives, anti-diarrheals, probiotics, and ORS.' },
  { id: 'cat-12', name: 'Respiratory Health', description: 'Nebulizers, bronchodilators, and pulmonary care.' },
  { id: 'cat-13', name: 'First Aid & Antiseptics', description: 'Bandages, antiseptics, cotton rolls, and burn gels.' },
  { id: 'cat-14', name: 'Pediatric Care', description: 'Child-safe drops, syrups, and pediatric supplements.' },
  { id: 'cat-15', name: 'Medical Devices', description: 'Thermometers, BP monitors, pulse oximeters, glucometers.' },
];

export const initialSuppliers = [
  {
    id: 'SUP-001',
    companyName: 'Apex Health Distributors',
    contactPerson: 'Robert Sterling',
    phone: '+1 (555) 234-5678',
    email: 'contact@apexhealth.com',
    address: '450 Industrial Parkway, Metro City',
    gstTaxId: 'GST-USA-98214',
    medicinesSupplied: ['Paracetamol 500mg', 'Amoxicillin 500mg', 'Omeprazole 20mg'],
    totalPurchases: 12500.00,
    lastPurchaseDate: '2026-08-28'
  },
  {
    id: 'SUP-002',
    companyName: 'SunBio Pharmaceuticals',
    contactPerson: 'Elena Rostova',
    phone: '+1 (555) 876-5432',
    email: 'orders@sunbiopharma.org',
    address: '12 Science Park Drive, Tech Valley',
    gstTaxId: 'GST-USA-44109',
    medicinesSupplied: ['Cetirizine 10mg', 'Azithromycin 500mg', 'Multivitamin Capsules'],
    totalPurchases: 8900.50,
    lastPurchaseDate: '2026-09-02'
  },
  {
    id: 'SUP-003',
    companyName: 'MedLife Global Wholesale',
    contactPerson: 'David Chen',
    phone: '+1 (555) 998-1122',
    email: 'supply@medlifeglobal.com',
    address: '88 Logistics Blvd, Harbor City',
    gstTaxId: 'GST-USA-33921',
    medicinesSupplied: ['Metformin 500mg', 'Amlodipine 5mg', 'Atorvastatin 20mg', 'Salbutamol Inhaler'],
    totalPurchases: 18450.00,
    lastPurchaseDate: '2026-09-05'
  },
  {
    id: 'SUP-004',
    companyName: 'CarePlus Surgical & Equipment',
    contactPerson: 'Amanda Vance',
    phone: '+1 (555) 443-8899',
    email: 'info@careplussurgical.com',
    address: '102 Medical Hub Center, Westside',
    gstTaxId: 'GST-USA-77812',
    medicinesSupplied: ['Digital Thermometer', 'Blood Pressure Monitor', 'ORS Powder Sachet'],
    totalPurchases: 6200.00,
    lastPurchaseDate: '2026-08-15'
  }
];

export const initialMedicines = [
  {
    id: 'MED-1001',
    name: 'Paracetamol 500mg',
    genericName: 'Acetaminophen / Paracetamol',
    brandName: 'Crocin / Panadol',
    category: 'Fever & Antipyretics',
    medicineType: 'Tablet',
    description: 'Fast-acting analgesics and fever reducer used for mild to moderate pain.',
    manufacturer: 'Apex Pharma Labs',
    supplierId: 'SUP-001',
    supplierName: 'Apex Health Distributors',
    purchasePrice: 1.20,
    sellingPrice: 3.50,
    currentStock: 130,
    minStockLevel: 30,
    maxStockLevel: 500,
    prescriptionRequired: false,
    storageInstructions: 'Store in a cool, dry place below 25°C away from direct sunlight.',
    status: 'Available',
    generalUses: 'Relief of mild pain, fever reduction, headache, toothache, and body aches.',
    generalPrecautions: 'Do not exceed maximum daily dosage (4g/day). Avoid alcohol during use. Consult pharmacist if liver conditions exist.',
    sideEffects: 'Nausea, allergic skin rash (rare), elevated liver enzymes with overuse.',
    warnings: 'Overdose may cause severe liver damage. Seek immediate emergency care if accidental overdose occurs.'
  },
  {
    id: 'MED-1002',
    name: 'Amoxicillin 500mg',
    genericName: 'Amoxicillin Trihydrate',
    brandName: 'Moxatag / Amoxil',
    category: 'Cold & Cough',
    medicineType: 'Capsule',
    description: 'Broad-spectrum penicillin antibiotic for bacterial infections.',
    manufacturer: 'Apex Pharma Labs',
    supplierId: 'SUP-001',
    supplierName: 'Apex Health Distributors',
    purchasePrice: 4.50,
    sellingPrice: 12.00,
    currentStock: 45,
    minStockLevel: 20,
    maxStockLevel: 200,
    prescriptionRequired: true,
    storageInstructions: 'Store below 30°C in airtight container.',
    status: 'Available',
    generalUses: 'Treats bacterial throat infections, ear infections, respiratory tract infections.',
    generalPrecautions: 'Take complete course as prescribed. Do not stop early even if feeling better.',
    sideEffects: 'Mild diarrhea, nausea, skin rash, stomach upset.',
    warnings: 'Contraindicated for patients allergic to penicillin. Seek medical help if severe rash or anaphylaxis develops.'
  },
  {
    id: 'MED-1003',
    name: 'Cetirizine 10mg',
    genericName: 'Cetirizine Hydrochloride',
    brandName: 'Zyrtec / Alerid',
    category: 'Allergy & Asthma',
    medicineType: 'Tablet',
    description: 'Second-generation non-drowsy antihistamine for allergy symptoms.',
    manufacturer: 'SunBio Health',
    supplierId: 'SUP-002',
    supplierName: 'SunBio Pharmaceuticals',
    purchasePrice: 2.00,
    sellingPrice: 6.00,
    currentStock: 18,
    minStockLevel: 25,
    maxStockLevel: 300,
    prescriptionRequired: false,
    storageInstructions: 'Keep in original blister pack away from moisture.',
    status: 'Low Stock',
    generalUses: 'Relief from allergic rhinitis, sneezing, watery eyes, hives, and itching.',
    generalPrecautions: 'May cause mild drowsiness in sensitive individuals. Avoid driving if feeling sleepy.',
    sideEffects: 'Dry mouth, fatigue, headache, mild somnolence.',
    warnings: 'Use caution in kidney dysfunction. Consult pharmacist for proper pediatric dosage.'
  },
  {
    id: 'MED-1004',
    name: 'Omeprazole 20mg',
    genericName: 'Omeprazole',
    brandName: 'Prilosec / Omez',
    category: 'Gastric & Acidity',
    medicineType: 'Capsule',
    description: 'Proton pump inhibitor that decreases stomach acid production.',
    manufacturer: 'Apex Pharma Labs',
    supplierId: 'SUP-001',
    supplierName: 'Apex Health Distributors',
    purchasePrice: 3.20,
    sellingPrice: 9.50,
    currentStock: 80,
    minStockLevel: 20,
    maxStockLevel: 250,
    prescriptionRequired: false,
    storageInstructions: 'Store at room temperature in light-resistant container.',
    status: 'Available',
    generalUses: 'Heartburn, GERD, acid reflux, and stomach ulcers.',
    generalPrecautions: 'Take 30 minutes before first meal of the day. Do not crush capsules.',
    sideEffects: 'Headache, abdominal pain, diarrhea, flatulence.',
    warnings: 'Long-term unmonitored use may affect B12 and magnesium absorption.'
  },
  {
    id: 'MED-1005',
    name: 'Metformin 500mg',
    genericName: 'Metformin Hydrochloride',
    brandName: 'Glucophage / Glycomet',
    category: 'Diabetes Care',
    medicineType: 'Tablet',
    description: 'First-line oral blood glucose lowering medication for Type 2 Diabetes.',
    manufacturer: 'MedLife Corp',
    supplierId: 'SUP-003',
    supplierName: 'MedLife Global Wholesale',
    purchasePrice: 2.80,
    sellingPrice: 8.00,
    currentStock: 200,
    minStockLevel: 40,
    maxStockLevel: 600,
    prescriptionRequired: true,
    storageInstructions: 'Store between 15°C and 30°C.',
    status: 'Available',
    generalUses: 'Blood sugar control in Type 2 Diabetes mellitus.',
    generalPrecautions: 'Take with meals to minimize stomach upset. Stay well hydrated.',
    sideEffects: 'Nausea, metallic taste, diarrhea, abdominal cramping.',
    warnings: 'Risk of lactic acidosis in kidney impairment. Seek emergency care if severe weakness or breathing distress occurs.'
  },
  {
    id: 'MED-1006',
    name: 'Azithromycin 500mg',
    genericName: 'Azithromycin Dihydrate',
    brandName: 'Zithromax / Azithral',
    category: 'Cold & Cough',
    medicineType: 'Tablet',
    description: 'Macrolide antibiotic for respiratory and soft tissue bacterial infections.',
    manufacturer: 'SunBio Health',
    supplierId: 'SUP-002',
    supplierName: 'SunBio Pharmaceuticals',
    purchasePrice: 5.50,
    sellingPrice: 15.00,
    currentStock: 0,
    minStockLevel: 15,
    maxStockLevel: 150,
    prescriptionRequired: true,
    storageInstructions: 'Store in dry place away from heat.',
    status: 'Out of Stock',
    generalUses: 'Short-course antibiotic for bronchitis, sinusitis, pneumonia, skin infections.',
    generalPrecautions: 'Prescription mandatory. Follow exact 3 or 5 day treatment course.',
    sideEffects: 'Stomach upset, diarrhea, dizziness, temporary taste change.',
    warnings: 'Inform doctor if you have history of cardiac arrhythmia or liver issues.'
  },
  {
    id: 'MED-1007',
    name: 'Cough Clear Syrup 100ml',
    genericName: 'Dextromethorphan + Chlorpheniramine',
    brandName: 'Benadryl / Ascoril',
    category: 'Cold & Cough',
    medicineType: 'Syrup',
    description: 'Soothes dry cough, tickly throat, and nasal congestion.',
    manufacturer: 'SunBio Health',
    supplierId: 'SUP-002',
    supplierName: 'SunBio Pharmaceuticals',
    purchasePrice: 2.50,
    sellingPrice: 7.50,
    currentStock: 65,
    minStockLevel: 20,
    maxStockLevel: 200,
    prescriptionRequired: false,
    storageInstructions: 'Store below 25°C. Do not freeze.',
    status: 'Available',
    generalUses: 'Relief of dry non-productive cough, throat irritation, and sneezing.',
    generalPrecautions: 'Shake well before use. Use measuring cup provided.',
    sideEffects: 'Mild drowsiness, dizziness, constipation.',
    warnings: 'Do not combine with alcohol or sedative medicines.'
  },
  {
    id: 'MED-1008',
    name: 'Multivitamin & Zinc Capsules',
    genericName: 'Multivitamins + Minerals + Zinc',
    brandName: 'Zincovit / Becosules',
    category: 'Vitamins & Supplements',
    medicineType: 'Capsule',
    description: 'Comprehensive daily nutritional supplement for immunity and energy support.',
    manufacturer: 'SunBio Health',
    supplierId: 'SUP-002',
    supplierName: 'SunBio Pharmaceuticals',
    purchasePrice: 3.00,
    sellingPrice: 9.00,
    currentStock: 110,
    minStockLevel: 25,
    maxStockLevel: 400,
    prescriptionRequired: false,
    storageInstructions: 'Store in cool dry place below 25°C.',
    status: 'Available',
    generalUses: 'Immunity boosting, recovery after illness, nutritional deficiency prevention.',
    generalPrecautions: 'Take one capsule daily after breakfast with water.',
    sideEffects: 'Mild stomach nausea if taken on empty stomach.',
    warnings: 'Dietary supplement. Not intended to replace a balanced diet.'
  },
  {
    id: 'MED-1009',
    name: 'Hydrocortisone 1% Cream 20g',
    genericName: 'Hydrocortisone Acetate',
    brandName: 'Cortizone / Dermacort',
    category: 'Skin Care & Ointments',
    medicineType: 'Cream',
    description: 'Mild topical corticosteroid for skin redness, itching, and inflammation.',
    manufacturer: 'Apex Pharma Labs',
    supplierId: 'SUP-001',
    supplierName: 'Apex Health Distributors',
    purchasePrice: 2.20,
    sellingPrice: 6.80,
    currentStock: 12,
    minStockLevel: 15,
    maxStockLevel: 100,
    prescriptionRequired: false,
    storageInstructions: 'Store below 25°C. Keep tube tightly closed.',
    status: 'Low Stock',
    generalUses: 'Relief of eczema, insect bites, contact dermatitis, minor rashes.',
    generalPrecautions: 'Apply thin layer to affected area 1-2 times daily. Avoid contact with eyes.',
    sideEffects: 'Mild burning, skin dryness or thinning with prolonged use.',
    warnings: 'Do not use on open wounds or untreated skin infections.'
  },
  {
    id: 'MED-1010',
    name: 'Salbutamol Inhaler 100mcg',
    genericName: 'Salbutamol / Albuterol',
    brandName: 'Ventolin / Asthalin',
    category: 'Respiratory Health',
    medicineType: 'Inhaler',
    description: 'Fast-acting bronchodilator for acute asthma symptoms and bronchospasm.',
    manufacturer: 'MedLife Corp',
    supplierId: 'SUP-003',
    supplierName: 'MedLife Global Wholesale',
    purchasePrice: 6.00,
    sellingPrice: 18.50,
    currentStock: 35,
    minStockLevel: 10,
    maxStockLevel: 100,
    prescriptionRequired: true,
    storageInstructions: 'Store below 30°C away from direct heat and sunlight. Do not puncture canister.',
    status: 'Available',
    generalUses: 'Emergency relief of wheezing, shortness of breath, and asthma attacks.',
    generalPrecautions: 'Always carry inhaler with you. Rinse mouth with water after inhalation.',
    sideEffects: 'Fine tremor in hands, rapid heart rate (palpitations), headache.',
    warnings: 'If shortness of breath fails to improve after 2-4 puffs, seek emergency medical care immediately.'
  },
  {
    id: 'MED-1011',
    name: 'Digital Clinical Thermometer',
    genericName: 'Electronic Body Thermometer',
    brandName: 'Omron / Dr. Morepen',
    category: 'Medical Devices',
    medicineType: 'Medical Device',
    description: 'High-accuracy digital thermometer with fever alarm beep and auto memory.',
    manufacturer: 'CarePlus Technologies',
    supplierId: 'SUP-004',
    supplierName: 'CarePlus Surgical & Equipment',
    purchasePrice: 4.00,
    sellingPrice: 12.50,
    currentStock: 25,
    minStockLevel: 10,
    maxStockLevel: 100,
    prescriptionRequired: false,
    storageInstructions: 'Keep in protective hard case when not in use.',
    status: 'Available',
    generalUses: 'Accurate oral, axillary, or rectal body temperature measurement.',
    generalPrecautions: 'Clean probe tip with alcohol swab before and after each use.',
    sideEffects: 'None.',
    warnings: 'Do not drop or expose device to high temperatures or liquids.'
  },
  {
    id: 'MED-1012',
    name: 'Electrolyte ORS Powder 21.8g',
    genericName: 'Oral Rehydration Salts (WHO Formula)',
    brandName: 'Electral / Pedialyte',
    category: 'Digestive Health',
    medicineType: 'Powder',
    description: 'Balanced electrolyte rehydration powder for fluid loss due to diarrhea and fever.',
    manufacturer: 'CarePlus Technologies',
    supplierId: 'SUP-004',
    supplierName: 'CarePlus Surgical & Equipment',
    purchasePrice: 0.40,
    sellingPrice: 1.50,
    currentStock: 300,
    minStockLevel: 50,
    maxStockLevel: 1000,
    prescriptionRequired: false,
    storageInstructions: 'Store in dry place. Once dissolved in 1 liter water, consume within 24 hours.',
    status: 'Available',
    generalUses: 'Prevention and treatment of dehydration from diarrhea, vomiting, heat stroke.',
    generalPrecautions: 'Dissolve entire sachet in exactly 1 liter of boiled & cooled drinking water.',
    sideEffects: 'None when mixed with correct water volume.',
    warnings: 'In severe dehydration with lethargy or inability to drink, hospital IV fluids are urgent.'
  },
  {
    id: 'MED-1013',
    name: 'Amlodipine 5mg',
    genericName: 'Amlodipine Besylate',
    brandName: 'Norvasc / Amlopress',
    category: 'Blood Pressure & Heart',
    medicineType: 'Tablet',
    description: 'Calcium channel blocker for hypertension and chest pain (angina).',
    manufacturer: 'MedLife Corp',
    supplierId: 'SUP-003',
    supplierName: 'MedLife Global Wholesale',
    purchasePrice: 2.10,
    sellingPrice: 6.50,
    currentStock: 95,
    minStockLevel: 25,
    maxStockLevel: 300,
    prescriptionRequired: true,
    storageInstructions: 'Store between 15°C and 30°C.',
    status: 'Available',
    generalUses: 'Long-term management of high blood pressure and coronary artery disease.',
    generalPrecautions: 'Take daily at the same time. Do not discontinue suddenly.',
    sideEffects: 'Ankle swelling (edema), dizziness, flushing, fatigue.',
    warnings: 'Requires routine medical supervision and BP monitoring.'
  },
  {
    id: 'MED-1014',
    name: 'Eye Lubricant Drops 10ml',
    genericName: 'Carboxymethylcellulose 0.5%',
    brandName: 'Refresh Tears / TearDrops',
    category: 'Eye & Ear Care',
    medicineType: 'Drops',
    description: 'Soothing artificial tears for dry, fatigued, or irritated eyes.',
    manufacturer: 'Apex Pharma Labs',
    supplierId: 'SUP-001',
    supplierName: 'Apex Health Distributors',
    purchasePrice: 1.80,
    sellingPrice: 5.50,
    currentStock: 8,
    minStockLevel: 15,
    maxStockLevel: 120,
    prescriptionRequired: false,
    storageInstructions: 'Discard 30 days after opening. Store below 25°C.',
    status: 'Low Stock',
    generalUses: 'Relief of eye dryness caused by computer screen use, wind, dust, air conditioning.',
    generalPrecautions: 'Do not touch dropper tip to eye or skin surface to prevent contamination.',
    sideEffects: 'Transient blurred vision right after instillation.',
    warnings: 'If eye pain or vision change persists over 72 hours, consult an ophthalmologist.'
  },
  {
    id: 'MED-1015',
    name: 'Vitamin D3 60,000 IU',
    genericName: 'Cholecalciferol',
    brandName: 'Calcirol / Uprise D3',
    category: 'Vitamins & Supplements',
    medicineType: 'Sachet',
    description: 'High-potency weekly Vitamin D3 supplement for bone health and deficiency.',
    manufacturer: 'SunBio Health',
    supplierId: 'SUP-002',
    supplierName: 'SunBio Pharmaceuticals',
    purchasePrice: 1.50,
    sellingPrice: 5.00,
    currentStock: 140,
    minStockLevel: 30,
    maxStockLevel: 400,
    prescriptionRequired: false,
    storageInstructions: 'Store in cool place away from moisture.',
    status: 'Available',
    generalUses: 'Treatment of Vitamin D deficiency, osteoporosis support, calcium absorption.',
    generalPrecautions: 'Take weekly with milk or after fatty meals for maximum absorption.',
    sideEffects: 'Hypercalcemia symptoms only if gross overdose occurs.',
    warnings: 'Check serum Vitamin D levels periodically when taking high doses.'
  }
];

export const initialBatches = [
  {
    id: 'BAT-1001A',
    medicineId: 'MED-1001',
    medicineName: 'Paracetamol 500mg',
    batchNumber: 'BATCH-PAR-2026A',
    quantity: 100,
    mfgDate: '2025-06-15',
    expiryDate: '2027-01-30',
    purchasePrice: 1.20,
    supplierId: 'SUP-001',
    supplierName: 'Apex Health Distributors',
    invoiceNumber: 'INV-APX-9901'
  },
  {
    id: 'BAT-1001B',
    medicineId: 'MED-1001',
    medicineName: 'Paracetamol 500mg',
    batchNumber: 'BATCH-PAR-2026B',
    quantity: 30,
    mfgDate: '2025-09-10',
    expiryDate: '2027-06-30',
    purchasePrice: 1.20,
    supplierId: 'SUP-001',
    supplierName: 'Apex Health Distributors',
    invoiceNumber: 'INV-APX-9988'
  },
  {
    id: 'BAT-1002A',
    medicineId: 'MED-1002',
    medicineName: 'Amoxicillin 500mg',
    batchNumber: 'BATCH-AMX-2026X',
    quantity: 45,
    mfgDate: '2025-03-01',
    expiryDate: '2026-10-15',
    purchasePrice: 4.50,
    supplierId: 'SUP-001',
    supplierName: 'Apex Health Distributors',
    invoiceNumber: 'INV-APX-8812'
  },
  {
    id: 'BAT-1003A',
    medicineId: 'MED-1003',
    medicineName: 'Cetirizine 10mg',
    batchNumber: 'BATCH-CET-2026M',
    quantity: 18,
    mfgDate: '2025-01-10',
    expiryDate: '2026-09-25', // Near expiry (within 30 days of Sept 2026)
    purchasePrice: 2.00,
    supplierId: 'SUP-002',
    supplierName: 'SunBio Pharmaceuticals',
    invoiceNumber: 'INV-SUN-4411'
  },
  {
    id: 'BAT-1004A',
    medicineId: 'MED-1004',
    medicineName: 'Omeprazole 20mg',
    batchNumber: 'BATCH-OMP-2027',
    quantity: 80,
    mfgDate: '2025-07-01',
    expiryDate: '2027-08-30',
    purchasePrice: 3.20,
    supplierId: 'SUP-001',
    supplierName: 'Apex Health Distributors',
    invoiceNumber: 'INV-APX-7711'
  },
  {
    id: 'BAT-1005A',
    medicineId: 'MED-1005',
    medicineName: 'Metformin 500mg',
    batchNumber: 'BATCH-MET-2027K',
    quantity: 200,
    mfgDate: '2025-05-12',
    expiryDate: '2027-11-20',
    purchasePrice: 2.80,
    supplierId: 'SUP-003',
    supplierName: 'MedLife Global Wholesale',
    invoiceNumber: 'INV-MLG-1029'
  },
  {
    id: 'BAT-1007A',
    medicineId: 'MED-1007',
    medicineName: 'Cough Clear Syrup 100ml',
    batchNumber: 'BATCH-SYR-2026',
    quantity: 65,
    mfgDate: '2025-04-10',
    expiryDate: '2026-11-15',
    purchasePrice: 2.50,
    supplierId: 'SUP-002',
    supplierName: 'SunBio Pharmaceuticals',
    invoiceNumber: 'INV-SUN-3320'
  },
  {
    id: 'BAT-1008A',
    medicineId: 'MED-1008',
    medicineName: 'Multivitamin & Zinc Capsules',
    batchNumber: 'BATCH-VMS-2028',
    quantity: 110,
    mfgDate: '2025-08-01',
    expiryDate: '2028-02-28',
    purchasePrice: 3.00,
    supplierId: 'SUP-002',
    supplierName: 'SunBio Pharmaceuticals',
    invoiceNumber: 'INV-SUN-5561'
  },
  {
    id: 'BAT-1009A',
    medicineId: 'MED-1009',
    medicineName: 'Hydrocortisone 1% Cream 20g',
    batchNumber: 'BATCH-HYD-2026E',
    quantity: 12,
    mfgDate: '2024-08-01',
    expiryDate: '2026-08-15', // Expired
    purchasePrice: 2.20,
    supplierId: 'SUP-001',
    supplierName: 'Apex Health Distributors',
    invoiceNumber: 'INV-APX-6091'
  },
  {
    id: 'BAT-1010A',
    medicineId: 'MED-1010',
    medicineName: 'Salbutamol Inhaler 100mcg',
    batchNumber: 'BATCH-INH-2027',
    quantity: 35,
    mfgDate: '2025-02-10',
    expiryDate: '2027-04-10',
    purchasePrice: 6.00,
    supplierId: 'SUP-003',
    supplierName: 'MedLife Global Wholesale',
    invoiceNumber: 'INV-MLG-8812'
  },
  {
    id: 'BAT-1011A',
    medicineId: 'MED-1011',
    medicineName: 'Digital Clinical Thermometer',
    batchNumber: 'BATCH-DEV-2030',
    quantity: 25,
    mfgDate: '2025-01-01',
    expiryDate: '2030-12-31',
    purchasePrice: 4.00,
    supplierId: 'SUP-004',
    supplierName: 'CarePlus Surgical & Equipment',
    invoiceNumber: 'INV-CPS-2201'
  },
  {
    id: 'BAT-1012A',
    medicineId: 'MED-1012',
    medicineName: 'Electrolyte ORS Powder 21.8g',
    batchNumber: 'BATCH-ORS-2027',
    quantity: 300,
    mfgDate: '2025-06-01',
    expiryDate: '2027-06-01',
    purchasePrice: 0.40,
    supplierId: 'SUP-004',
    supplierName: 'CarePlus Surgical & Equipment',
    invoiceNumber: 'INV-CPS-9912'
  },
  {
    id: 'BAT-1013A',
    medicineId: 'MED-1013',
    medicineName: 'Amlodipine 5mg',
    batchNumber: 'BATCH-AML-2027',
    quantity: 95,
    mfgDate: '2025-05-01',
    expiryDate: '2027-07-31',
    purchasePrice: 2.10,
    supplierId: 'SUP-003',
    supplierName: 'MedLife Global Wholesale',
    invoiceNumber: 'INV-MLG-5501'
  },
  {
    id: 'BAT-1014A',
    medicineId: 'MED-1014',
    medicineName: 'Eye Lubricant Drops 10ml',
    batchNumber: 'BATCH-EYE-2026',
    quantity: 8,
    mfgDate: '2025-01-15',
    expiryDate: '2026-10-30',
    purchasePrice: 1.80,
    supplierId: 'SUP-001',
    supplierName: 'Apex Health Distributors',
    invoiceNumber: 'INV-APX-3310'
  },
  {
    id: 'BAT-1015A',
    medicineId: 'MED-1015',
    medicineName: 'Vitamin D3 60,000 IU',
    batchNumber: 'BATCH-VIT-2028',
    quantity: 140,
    mfgDate: '2025-07-15',
    expiryDate: '2028-07-15',
    purchasePrice: 1.50,
    supplierId: 'SUP-002',
    supplierName: 'SunBio Pharmaceuticals',
    invoiceNumber: 'INV-SUN-7700'
  }
];

export const initialSales = [
  {
    id: 'SALE-10001',
    invoiceNumber: 'INV-2026-0001',
    date: '2026-09-08T14:30:00Z',
    customerName: 'Walk-in Customer (John Doe)',
    customerPhone: '+1 (555) 777-1234',
    items: [
      { medicineId: 'MED-1001', medicineName: 'Paracetamol 500mg', batchNumber: 'BATCH-PAR-2026A', quantity: 2, unitPrice: 3.50, totalPrice: 7.00 },
      { medicineId: 'MED-1007', medicineName: 'Cough Clear Syrup 100ml', batchNumber: 'BATCH-SYR-2026', quantity: 1, unitPrice: 7.50, totalPrice: 7.50 }
    ],
    subtotal: 14.50,
    discountAmount: 0.50,
    taxAmount: 0.70,
    totalAmount: 14.70,
    paymentMethod: 'Cash',
    soldBy: 'Pharmacist Sarah',
    status: 'Completed'
  },
  {
    id: 'SALE-10002',
    invoiceNumber: 'INV-2026-0002',
    date: '2026-09-08T16:15:00Z',
    customerName: 'Emily Clark',
    customerPhone: '+1 (555) 333-8822',
    items: [
      { medicineId: 'MED-1008', medicineName: 'Multivitamin & Zinc Capsules', batchNumber: 'BATCH-VMS-2028', quantity: 2, unitPrice: 9.00, totalPrice: 18.00 },
      { medicineId: 'MED-1012', medicineName: 'Electrolyte ORS Powder 21.8g', batchNumber: 'BATCH-ORS-2027', quantity: 5, unitPrice: 1.50, totalPrice: 7.50 }
    ],
    subtotal: 25.50,
    discountAmount: 1.50,
    taxAmount: 1.20,
    totalAmount: 25.20,
    paymentMethod: 'Card',
    soldBy: 'Admin Mark',
    status: 'Completed'
  }
];

export const initialPurchases = [
  {
    id: 'PUR-2026-001',
    invoiceNumber: 'INV-APX-9988',
    date: '2026-09-01',
    supplierId: 'SUP-001',
    supplierName: 'Apex Health Distributors',
    items: [
      { medicineId: 'MED-1001', medicineName: 'Paracetamol 500mg', batchNumber: 'BATCH-PAR-2026B', quantity: 50, purchasePrice: 1.20, total: 60.00 }
    ],
    totalAmount: 60.00,
    status: 'Received',
    receivedBy: 'Admin Mark'
  },
  {
    id: 'PUR-2026-002',
    invoiceNumber: 'INV-SUN-5561',
    date: '2026-09-02',
    supplierId: 'SUP-002',
    supplierName: 'SunBio Pharmaceuticals',
    items: [
      { medicineId: 'MED-1008', medicineName: 'Multivitamin & Zinc Capsules', batchNumber: 'BATCH-VMS-2028', quantity: 100, purchasePrice: 3.00, total: 300.00 }
    ],
    totalAmount: 300.00,
    status: 'Received',
    receivedBy: 'Pharmacist Sarah'
  }
];

export const initialOrders = [
  {
    id: 'ORD-8801',
    customerName: 'Alice Miller',
    email: 'alice.m@example.com',
    phone: '+1 (555) 654-3210',
    deliveryAddress: '742 Evergreen Terrace, Springfield',
    date: '2026-09-08T18:40:00Z',
    items: [
      { medicineId: 'MED-1002', name: 'Amoxicillin 500mg', quantity: 1, price: 12.00, prescriptionRequired: true },
      { medicineId: 'MED-1001', name: 'Paracetamol 500mg', quantity: 2, price: 3.50, prescriptionRequired: false }
    ],
    totalAmount: 19.00,
    prescriptionUploaded: true,
    prescriptionFileUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500',
    prescriptionVerified: false,
    status: 'Prescription Verification',
    paymentMethod: 'Credit Card (Paid)'
  },
  {
    id: 'ORD-8802',
    customerName: 'Marcus Wright',
    email: 'marcus.w@example.com',
    phone: '+1 (555) 912-3344',
    deliveryAddress: '120 Baker Street, Suite 4B',
    date: '2026-09-07T11:20:00Z',
    items: [
      { medicineId: 'MED-1004', name: 'Omeprazole 20mg', quantity: 2, price: 9.50, prescriptionRequired: false },
      { medicineId: 'MED-1008', name: 'Multivitamin & Zinc Capsules', quantity: 1, price: 9.00, prescriptionRequired: false }
    ],
    totalAmount: 28.00,
    prescriptionUploaded: false,
    prescriptionVerified: true,
    status: 'Delivered',
    paymentMethod: 'Cash on Delivery'
  }
];

export const initialHealthTopics = [
  {
    id: 'HLT-001',
    condition: 'Fever & Elevated Body Temperature',
    category: 'Fever',
    overview: 'Fever is a temporary increase in body temperature, often due to an underlying immune response against infection.',
    commonSymptoms: ['Body temperature > 37.5°C (99.5°F)', 'Chills or shivering', 'Headache & muscle ache', 'Sweating & loss of appetite'],
    selfCareInfo: 'Rest adequately, drink plenty of fluids (water, ORS, soups) to prevent dehydration, and wear light clothing.',
    otcGuidance: 'Some over-the-counter fever reducers (like Paracetamol) may help manage fever symptoms in mild cases. Always verify dosage according to age, weight, and existing conditions. Consult a pharmacist or doctor before medication.',
    redFlagSymptoms: [
      'Fever > 39.4°C (103°F) or persisting for more than 3 days',
      'Severe stiff neck, confusion, or difficulty waking up',
      'Difficulty breathing or chest pain',
      'Fever in infants under 3 months old'
    ],
    whenToSeekDoctor: 'If red-flag symptoms are present, or fever does not respond to self-care within 48 hours.'
  },
  {
    id: 'HLT-002',
    condition: 'Common Cold & Sore Throat',
    category: 'Cold & Cough',
    overview: 'A viral infection of the upper respiratory tract affecting nose and throat.',
    commonSymptoms: ['Runny or stuffy nose', 'Sore throat or scratchiness', 'Sneezing & mild body discomfort', 'Mild cough'],
    selfCareInfo: 'Gargle with warm salt water, use a humidifier, consume warm tea with honey, and get extra rest.',
    otcGuidance: 'Over-the-counter decongestants, saline nasal sprays, and lozenges may soothe throat and nasal symptoms. Suitability depends on blood pressure, age, and health history. Consult a pharmacist for guidance.',
    redFlagSymptoms: [
      'Inability to swallow liquids or severe throat pain',
      'Shortness of breath or wheezing',
      'Symptoms worsening significantly after 7-10 days'
    ],
    whenToSeekDoctor: 'If high fever accompanies throat pain, or symptoms persist beyond 10 days.'
  },
  {
    id: 'HLT-003',
    condition: 'Acid Reflux & Heartburn',
    category: 'Gastric & Acidity',
    overview: 'A burning chest sensation caused by stomach acid flowing back into the esophagus.',
    commonSymptoms: ['Burning feeling in chest after eating', 'Acidic taste in throat or mouth', 'Bloating and upper abdominal discomfort'],
    selfCareInfo: 'Eat smaller, more frequent meals. Avoid lying down within 3 hours after eating. Avoid triggering foods like heavy fats, citrus, caffeine, and spicy items.',
    otcGuidance: 'Mild symptoms may respond to OTC antacids or H2 blockers. Frequent or severe symptoms require medical evaluation. Consult a healthcare provider.',
    redFlagSymptoms: [
      'Difficulty or pain when swallowing food',
      'Vomiting blood or black tarry stools',
      'Chest pain radiating to arm, neck, or jaw (may indicate heart issue)'
    ],
    whenToSeekDoctor: 'Immediate emergency evaluation for chest pain with sweating or arm numbness.'
  },
  {
    id: 'HLT-004',
    condition: 'Seasonal Allergies & Rhinitis',
    category: 'Allergy',
    overview: 'Immune system reaction to airborne environmental allergens like pollen, dust, or pet dander.',
    commonSymptoms: ['Sneezing fits', 'Itchy, watery eyes', 'Clear runny nose', 'Itchy roof of mouth or throat'],
    selfCareInfo: 'Keep windows closed during high pollen counts. Clean indoor air filters. Use saline nasal rinses to clear allergens.',
    otcGuidance: 'Non-drowsy OTC antihistamines or allergy drops may alleviate mild allergic rhinitis symptoms. Check with a pharmacist regarding potential medication interactions.',
    redFlagSymptoms: [
      'Swelling of lips, tongue, or throat',
      'Difficulty breathing or sudden wheezing (Anaphylaxis risk)',
      'Severe skin rash with facial swelling'
    ],
    whenToSeekDoctor: 'Seek emergency care immediately if experiencing lip swelling or airway tightness.'
  }
];

export const initialAuditLogs = [
  {
    id: 'LOG-5001',
    user: 'Super Admin',
    action: 'Stock Addition',
    entity: 'Paracetamol 500mg',
    date: '2026-09-08T10:15:00Z',
    details: 'Added 50 units under Batch BATCH-PAR-2026B via Invoice INV-APX-9988.',
    previousValue: '80 units',
    newValue: '130 units'
  },
  {
    id: 'LOG-5002',
    user: 'Pharmacist Sarah',
    action: 'Completed Sale',
    entity: 'Sale INV-2026-0001',
    date: '2026-09-08T14:30:00Z',
    details: 'Sold 2 units Paracetamol, 1 unit Cough Clear Syrup to walk-in customer.',
    previousValue: 'Stock: 132 Paracetamol',
    newValue: 'Stock: 130 Paracetamol'
  },
  {
    id: 'LOG-5003',
    user: 'Super Admin',
    action: 'Supplier Created',
    entity: 'CarePlus Surgical & Equipment',
    date: '2026-09-05T09:00:00Z',
    details: 'Added new medical device supplier SUP-004.',
    previousValue: 'N/A',
    newValue: 'SUP-004 Created'
  }
];

export const initialNotifications = [
  {
    id: 'NOTIF-1',
    title: 'Low Stock Alert',
    message: 'Cetirizine 10mg is low on stock (18 remaining, min level: 25).',
    type: 'warning',
    timestamp: '2026-09-08T17:00:00Z',
    read: false,
    link: '/inventory/low-stock'
  },
  {
    id: 'NOTIF-2',
    title: 'Expired Medicine Warning',
    message: 'Hydrocortisone 1% Cream 20g (Batch BATCH-HYD-2026E) has expired.',
    type: 'danger',
    timestamp: '2026-09-08T08:00:00Z',
    read: false,
    link: '/inventory/expired'
  },
  {
    id: 'NOTIF-3',
    title: 'Prescription Verification Required',
    message: 'New order #ORD-8801 requires prescription verification.',
    type: 'info',
    timestamp: '2026-09-08T18:40:00Z',
    read: false,
    link: '/orders'
  }
];
